<?php

namespace Nezyr;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
    public function onEnable(): void
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }
}